sonar.projectKey=ai-projects_ai_proofread_e1f96e80-f8dc-4146-abfd-c2772c95c396
sonar.qualitygate.wait=true
sonar.sources=app,services
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.coverage.exclusions=services/phonefmt.py,services/ner.py,services/llm.py,services/gsheets_client.py,services/phone_world_cc.py,app/modules/ner/**,app/modules/proofread/**,app/modules/result_analyse/**
